CREATE TABLE inventario (
    id INT PRIMARY KEY,
    editorial VARCHAR(255) NOT NULL,
    colegio VARCHAR(255) NOT NULL,
    codigo_centro VARCHAR(50) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NULL,
    bultos INT NULL,
    destino VARCHAR(50) NULL,
    `orden` VARCHAR(100) NULL,
    indicador_completa VARCHAR(100) NULL,
    estado ENUM('activo', 'historico', 'anulado') NOT NULL DEFAULT 'activo',
    fecha_confirmacion_salida DATETIME NULL,
    usuario_confirmacion_id INT NULL,
    usuario_confirmacion VARCHAR(100) NULL,
    usuario_anulacion_id INT NULL,
    usuario_anulacion VARCHAR(100) NULL,
    fecha_anulacion DATETIME NULL,
    motivo_anulacion VARCHAR(255) NULL,
    numero_albaran VARCHAR(50) NULL,
    sync_pendiente_historico TINYINT(1) NOT NULL DEFAULT 0,
    fecha_sync_historico DATETIME NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_inventario_estado (estado),
    INDEX idx_inventario_codigo_centro (codigo_centro),
    INDEX idx_inventario_numero_albaran (numero_albaran),
    INDEX idx_inventario_confirmacion (fecha_confirmacion_salida),
    INDEX idx_inventario_fecha_anulacion (fecha_anulacion),
    INDEX idx_inventario_sync_historico (estado, sync_pendiente_historico)
);
